### ISSUE TITLE
Question: Would you mind if I updated the specs/travis?

### ISSUE THREAD

**Issue by elskwid** [mwoods79/rippersnapper#8]
Hi there,

During my short work on #7 I noticed some inconsistencies in the spec files:
- single quote vs double quote
- some formatting
- possibly moving more to the `expect()` style rather than the implicit `subject` (although this is a matter of taste)

and I see that travis could have some newer Ruby versions added.

Rather than shove those into the feature PR I figured I'd ask here. Mind if I create a PR to address some of those things as well?

Thanks for the gem!

**Comment by mwoods79** [comment]
Please do.

**Comment by mwoods79** [comment]
Updated parens and .travis.yml

**Comment by elskwid** [comment]
@mwoods79 I have no idea why I didn't get notifications of your response. So sorry! Thanks for taking this feedback!
